Repository Erikang20/Kanban-task-management-web-app, pull requests merged in 2024-07, with the labels that each got.

#36 Adding the icons for the toggle option
  client/jsconfig.json
  client/package-lock.json
  client/package.json
  client/src/components/Sidebar/index.js
  client/src/components/Sidebar/index.jsx
  client/src/components/Sidebar/slider.jsx
  client/src/components/Sidebar/styles.module.scss
  client/src/components/Sidebar/useSidebar.js
Labels: frontend

#46 adding dummy data
  server/data.json
Labels: backend

#37 Toggle light/dark theme
  client/package-lock.json
  client/package.json
  client/src/components/Home/theme.jsx
  client/src/components/Sidebar/boardIcon.jsx
  client/src/components/Sidebar/index.jsx
  client/src/components/Sidebar/slider.jsx
  client/src/components/Sidebar/styles.module.scss
  client/src/components/core/SidebarButton/index.js
  client/src/components/core/SidebarButtons/index.jsx
  client/src/components/core/SidebarButtons/styles.module.scss
  client/src/components/core/index.js
  client/src/layout/index.jsx
Labels: frontend

#71 Feature/delete board : Added delete board confirmation modal
  client/package-lock.json
  client/package.json
  client/src/components/Header/ThreeDotsMenu.jsx
  client/src/components/core/Modals/DeleteBoardModal.js
  client/src/components/core/Modals/Modals.module.css
Labels: boards
